llmModelPath: "default/path/to/model"
systemPrompt: "Ваша задача заключается в том, чтобы тщательно проверять сообщения из чат-среды на предмет выявления нежелательного или вредного поведения. Каждое полученное вами сообщение должно быть внимательно проанализировано на предмет содержания, которое может быть расценено как оскорбительное, угрожающее, дискриминационное или иным образом неприемлемое. Ваши ответы должны быть четкими и прямыми. Если сообщение считается приемлемым и не нарушает никаких стандартов уважительного и безопасного общения, отвечайте ТОЛЬКО «ОК». Если сообщение определено как вредное, что включает в себя, но не ограничивается, издевательствами, речью ненависти, домогательством или любым видом агрессивного или неподобающего поведения, отвечайте ТОЛЬКО «ВРЕДНО» + причина. Помните, что ваша оценка должна строго категоризовать каждое сообщение либо как «ОК», либо как «ВРЕДНО», основываясь на содержании и контексте сообщения. Сообщение: "
warning_message: "§cВнимание: Данное сообщение было помечено как неприемлемое системой ИИ. Причина: "
startup_message: "Сервер API LLM был запущен."
llm_startup_error_message: "Не удалось запустить сервер API LLM: "
warning_message_template: "§9Сообщение: "
llm_response_message: "Содержимое ответа сервера API LLM: "
no_content_error_message: "Ответ сервера API LLM не содержит данных."
api_error_message: "Ошибка отправки сообщения на сервер API LLM: "
model_already_loaded_message: "Модель уже загружена."
failed_to_load_model_message: "Не удалось загрузить модель."
api_fail_message: "Не удалось отправить запрос на сервер API LLM: "
shutdown_message: "Сервер API LLM был остановлен."
model_not_loaded_message: "§cМодель еще не загружена. Пожалуйста, подождите..."
messages:
  inappropriateMessageCount: "§6%playerName% имеет %count% неприемлемых сообщений."
