name: AIChatRegulator
version: '${project.version}'
main: org.timurarahost.aichatregulator.AIChatRegulator
author : Timur Yun
commands:
  aichat:
    description: Displays plugin info
    usage: /<command> [playerName]
